export interface Question {
  id: number;
  text: string;
  options: [string, string, string, string];
  correct: 0 | 1 | 2 | 3; // index of correct answer
  subject: string;
}

export const QUESTIONS: Question[] = [
  { id: 1, text: "Quantos ângulos tem um triângulo?", options: ["4", "3", "2", "5"], correct: 1, subject: "Matemática" },
  { id: 2, text: "Quanto é 50 × 2?", options: ["75", "100", "125", "150"], correct: 1, subject: "Matemática" },
  { id: 3, text: "Qual é a capital do Brasil?", options: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador"], correct: 2, subject: "Geografia" },
  { id: 4, text: "Quanto é 25 + 38?", options: ["61", "63", "65", "60"], correct: 1, subject: "Matemática" },
  { id: 5, text: "Quantos dentes têm um adulto humano?", options: ["28", "30", "32", "34"], correct: 2, subject: "Ciências" },
  { id: 6, text: "Qual é o elemento mais abundante no universo?", options: ["Carbono", "Oxigênio", "Nitrogênio", "Hidrogênio"], correct: 3, subject: "Ciências" },
  { id: 7, text: "Em que ano o Brasil foi descoberto?", options: ["1492", "1500", "1510", "1498"], correct: 1, subject: "História" },
  { id: 8, text: "Quantos lados tem um hexágono?", options: ["4", "5", "6", "7"], correct: 2, subject: "Matemática" },
  { id: 9, text: "Qual é o maior planeta do sistema solar?", options: ["Saturno", "Urano", "Netuno", "Júpiter"], correct: 3, subject: "Ciências" },
  { id: 10, text: "Quanto é 9 × 7?", options: ["54", "56", "63", "72"], correct: 2, subject: "Matemática" },
  { id: 11, text: "Qual é o continente mais extenso?", options: ["América", "África", "Ásia", "Europa"], correct: 2, subject: "Geografia" },
  { id: 12, text: "Quantas letras tem o alfabeto português?", options: ["24", "25", "26", "28"], correct: 2, subject: "Português" },
  { id: 13, text: "Qual animal é conhecido como 'o rei da selva'?", options: ["Tigre", "Leão", "Leopardo", "Guepardo"], correct: 1, subject: "Ciências" },
  { id: 14, text: "Quanto é 144 ÷ 12?", options: ["10", "11", "12", "14"], correct: 2, subject: "Matemática" },
  { id: 15, text: "Qual é o rio mais longo do mundo?", options: ["Nilo", "Amazonas", "Mississippi", "Yangtze"], correct: 0, subject: "Geografia" },
  { id: 16, text: "Quantos meses têm 30 dias?", options: ["3", "4", "5", "6"], correct: 1, subject: "Matemática" },
  { id: 17, text: "Qual é o menor planeta do sistema solar?", options: ["Marte", "Vênus", "Mercúrio", "Plutão"], correct: 2, subject: "Ciências" },
  { id: 18, text: "Quanto é 15² (15 ao quadrado)?", options: ["125", "200", "225", "250"], correct: 2, subject: "Matemática" },
  { id: 19, text: "Qual país tem a maior população do mundo?", options: ["Índia", "China", "EUA", "Brasil"], correct: 0, subject: "Geografia" },
  { id: 20, text: "Quantos ossos tem o corpo humano adulto?", options: ["186", "206", "226", "246"], correct: 1, subject: "Ciências" },
  { id: 21, text: "Qual é o antônimo de 'alegre'?", options: ["Feliz", "Animado", "Triste", "Contente"], correct: 2, subject: "Português" },
  { id: 22, text: "Quanto é √64?", options: ["6", "7", "8", "9"], correct: 2, subject: "Matemática" },
  { id: 23, text: "Qual é a cor resultante da mistura de azul e amarelo?", options: ["Roxo", "Laranja", "Verde", "Marrom"], correct: 2, subject: "Ciências" },
  { id: 24, text: "Quantos dias tem um ano bissexto?", options: ["364", "365", "366", "367"], correct: 2, subject: "Matemática" },
  { id: 25, text: "Qual é a capital da França?", options: ["Lyon", "Marselha", "Nice", "Paris"], correct: 3, subject: "Geografia" },
  { id: 26, text: "Quanto é 7 × 8?", options: ["48", "54", "56", "64"], correct: 2, subject: "Matemática" },
  { id: 27, text: "Qual é o gás mais abundante na atmosfera terrestre?", options: ["Oxigênio", "Nitrogênio", "CO2", "Argônio"], correct: 1, subject: "Ciências" },
  { id: 28, text: "Qual instrumento mede a temperatura?", options: ["Barômetro", "Higrômetro", "Termômetro", "Anemômetro"], correct: 2, subject: "Ciências" },
  { id: 29, text: "Quantos continentes existem?", options: ["5", "6", "7", "8"], correct: 2, subject: "Geografia" },
  { id: 30, text: "Quanto é 1/4 de 200?", options: ["25", "40", "50", "75"], correct: 2, subject: "Matemática" },
  { id: 31, text: "Qual é o plural de 'leão'?", options: ["Leãos", "Leões", "Leons", "Leões"], correct: 1, subject: "Português" },
  { id: 32, text: "Qual planeta é conhecido como 'Planeta Vermelho'?", options: ["Saturno", "Vênus", "Marte", "Júpiter"], correct: 2, subject: "Ciências" },
  { id: 33, text: "Quanto é 3³ (3 ao cubo)?", options: ["9", "18", "27", "30"], correct: 2, subject: "Matemática" },
  { id: 34, text: "Qual é a maior floresta tropical do mundo?", options: ["Congo", "Amazônica", "Daintree", "Valdiviana"], correct: 1, subject: "Geografia" },
  { id: 35, text: "Quantas asas tem uma borboleta?", options: ["2", "4", "6", "8"], correct: 1, subject: "Ciências" },
  { id: 36, text: "Quanto é 1000 ÷ 25?", options: ["35", "40", "45", "50"], correct: 1, subject: "Matemática" },
  { id: 37, text: "Qual é o sinônimo de 'rápido'?", options: ["Lerdo", "Veloz", "Calmo", "Quieto"], correct: 1, subject: "Português" },
  { id: 38, text: "Qual é o órgão responsável pela circulação do sangue?", options: ["Pulmão", "Fígado", "Rim", "Coração"], correct: 3, subject: "Ciências" },
  { id: 39, text: "Quanto é 15% de 200?", options: ["20", "25", "30", "35"], correct: 2, subject: "Matemática" },
  { id: 40, text: "Qual é a capital da Argentina?", options: ["Córdoba", "Rosário", "Buenos Aires", "Mendoza"], correct: 2, subject: "Geografia" },
  { id: 41, text: "Quantas patas tem um inseto?", options: ["4", "6", "8", "10"], correct: 1, subject: "Ciências" },
  { id: 42, text: "Quanto é 2⁸ (2 elevado a 8)?", options: ["128", "256", "512", "64"], correct: 1, subject: "Matemática" },
  { id: 43, text: "Qual é o processo pelo qual plantas produzem alimento?", options: ["Respiração", "Fotossíntese", "Digestão", "Evaporação"], correct: 1, subject: "Ciências" },
  { id: 44, text: "Quantas horas tem um dia?", options: ["12", "20", "24", "48"], correct: 2, subject: "Matemática" },
  { id: 45, text: "Qual é o oceano mais profundo do mundo?", options: ["Atlântico", "Índico", "Ártico", "Pacífico"], correct: 3, subject: "Geografia" },
  { id: 46, text: "Quanto é 500 - 237?", options: ["253", "263", "273", "283"], correct: 1, subject: "Matemática" },
  { id: 47, text: "Qual é o menor número primo?", options: ["0", "1", "2", "3"], correct: 2, subject: "Matemática" },
  { id: 48, text: "Qual é o satélite natural da Terra?", options: ["Plutão", "Fobos", "Lua", "Titã"], correct: 2, subject: "Ciências" },
  { id: 49, text: "Quanto é 3/4 + 1/4?", options: ["1/2", "3/4", "1", "2"], correct: 2, subject: "Matemática" },
  { id: 50, text: "Qual é o animal mais rápido do mundo?", options: ["Leão", "Guepardo", "Falcão", "Coelho"], correct: 1, subject: "Ciências" },
];
